### ISSUE TITLE
Feature: Domain Layer Classes for Weather

### ISSUE THREAD

**Issue by xmcnulty** [xmcnulty/AvWx#11]
# Title

Feature: Domain Layer Classes for Weather

## Description

Create classes and objects representing weather conditions in METAR and TAF reports.

### Tasks

- [ ]  Create Domain/Model classes representing weather conditions
- [ ]  Create Domain/Model class representing METAR report
- [ ]  Create Domain/Model class representing TAF report
