### ISSUE TITLE
[FEATURE] METAR Summary

### ISSUE THREAD

**Issue by xmcnulty** [xmcnulty/AvWx#53]
**Is your feature request related to a problem? Please describe.**
No issues. But there should be an implemented ability to quickly get the summary of a METAR report from METAR data class that can be displayed in a list of search results from user search.

**Describe the solution you'd like**
Create a separate data class called MetarSummary such that:

`data class MetarSummary(val icao, val temp, val winds, val altimeter, val visibility)`

This summary should be retrievable form an extension function of the METAR class. Ex:

`val summary: MetarSummary = myMetar.getSummary()`

**Describe alternatives you've considered**
None.

**Additional context**
In addition to this issue, re-implement and structure logic for conversion from MetarDto to Metar, such that it is done in a file with extension functions, rather that in separate object classes.

### To-Do

- [x] Create MetarSummary Data class
- [x] Implement extension function for Metar that returns the summar
- [x] Unit testing
- [x] Move conversion logic for MetarDto -> Metar

**Comment by xmcnulty** [comment]
Made summary a property of the Metar class, such that it can be retrieved by calling `myMetar.summary`

Implemented MetarSummary data class with fields:

`data class MetarSummary(
    val icao: String,
    val time: MetarTime,
    val wind: Winds,
    val temp: Temperature,
    val rules: FlightRules,
    val visbility: Visibility
)`
